
import type { NewsArticle } from '@/types';

// Function to generate ISO strings for recent times
const timeAgo = (minutes: number) => new Date(Date.now() - minutes * 60 * 1000).toISOString();

export const dummyNewsData: Omit<NewsArticle, 'alertType'>[] = [
    { id: 'news_1', timestamp: timeAgo(1), symbol: 'TSLA', headline: 'Tesla Surges on Record Q2 Deliveries', sentiment: 'Positive', provider: 'Bloomberg', preview: 'Shares of Tesla jumped over 8% after the company reported delivering a record number of vehicles in the second quarter, beating analyst expectations.' },
    { id: 'news_2', timestamp: timeAgo(2), symbol: 'AAPL', headline: 'Apple Announces New iPhone Event', sentiment: 'Neutral', provider: 'CNBC', preview: 'Apple has sent out invitations for its annual hardware event, where it is widely expected to unveil the next generation of iPhone models.' },
    { id: 'news_3', timestamp: timeAgo(4), symbol: 'NVDA', headline: 'Nvidia Stock Hits All-Time High', sentiment: 'Positive', provider: 'Reuters', preview: 'Nvidia Corporation reached a new all-time high as demand for its AI chips continues to surge across the tech industry.' },
    { id: 'news_4', timestamp: timeAgo(6), symbol: 'GOOGL', headline: 'Google Under Antitrust Scrutiny Again', sentiment: 'Negative', provider: 'WSJ', preview: 'The Department of Justice is reportedly preparing another antitrust lawsuit against Google, this time targeting its advertising technology business.' },
    { id: 'news_5', timestamp: timeAgo(10), symbol: 'MSFT', headline: 'Microsoft Teams Outage Impacts Users', sentiment: 'Negative', provider: 'The Verge', preview: 'A widespread outage of Microsoft Teams has left millions of users unable to access the popular collaboration platform.' },
    { id: 'news_6', timestamp: timeAgo(15), symbol: 'META', headline: 'Meta Expands Threads Features', sentiment: 'Neutral', provider: 'TechCrunch', preview: 'Meta is rolling out several new features for its Threads app, including a much-requested chronological feed option.' },
    { id: 'news_7', timestamp: timeAgo(20), symbol: 'AMZN', headline: 'Amazon Launches Same-Day Grocery', sentiment: 'Positive', provider: 'CNBC', preview: 'Amazon is expanding its grocery delivery service to include same-day delivery from Whole Foods Market in more cities.' },
    { id: 'news_8', timestamp: timeAgo(30), symbol: 'NFLX', headline: 'Netflix Subscriber Growth Slows', sentiment: 'Negative', provider: 'Yahoo Finance', preview: 'Netflix reported subscriber growth that fell short of Wall Street estimates, raising concerns about its long-term growth trajectory.' },
    { id: 'news_9', timestamp: timeAgo(45), symbol: 'AMD', headline: 'AMD Announces Next-Gen Chip', sentiment: 'Positive', provider: 'MarketWatch', preview: 'Advanced Micro Devices unveiled its latest generation of processors, promising significant performance gains for PCs and servers.' },
    { id: 'news_10', timestamp: timeAgo(55), symbol: 'DIS', headline: 'Disney Reports Solid Earnings', sentiment: 'Positive', provider: 'Bloomberg', preview: 'The Walt Disney Company reported quarterly earnings that topped expectations, driven by strong performance in its parks division.' },
    { id: 'news_11', timestamp: timeAgo(65), symbol: 'JPM', headline: 'JPMorgan Raises Dividend', sentiment: 'Neutral', provider: 'Barrons', preview: 'JPMorgan Chase & Co. announced an increase to its quarterly dividend after successfully passing the Federal Reserve\'s annual stress test.' },
    { id: 'news_12', timestamp: timeAgo(75), symbol: 'BAC', headline: 'Bank of America Misses Estimates', sentiment: 'Negative', provider: 'Reuters', preview: 'Bank of America reported second-quarter profit that missed analyst estimates, citing a slowdown in investment banking activity.' },
    { id: 'news_13', timestamp: timeAgo(90), symbol: 'TSLA', headline: 'Tesla Recalls 10,000 Vehicles', sentiment: 'Negative', provider: 'CNBC', preview: 'Tesla is issuing a recall for approximately 10,000 Model Y and Model 3 vehicles due to a software issue with the seatbelt system.' },
    { id: 'news_14', timestamp: timeAgo(110), symbol: 'AAPL', headline: 'Apple Services Revenue Climbs', sentiment: 'Positive', provider: 'WSJ', preview: 'Apple\'s services division continues to be a bright spot, with revenue from the App Store, Apple Music, and iCloud showing robust growth.' },
    { id: 'news_15', timestamp: timeAgo(125), symbol: 'GOOGL', headline: 'Google Cloud Revenue Disappoints', sentiment: 'Negative', provider: 'TechCrunch', preview: 'While still growing, Google Cloud\'s revenue for the quarter came in below analyst expectations, sending Alphabet shares lower.' },
    { id: 'news_16', timestamp: timeAgo(140), symbol: 'UBER', headline: 'Uber stock downgraded on competition concerns', sentiment: 'Negative', provider: 'Yahoo Finance', preview: 'An analyst at Morgan Stanley has downgraded Uber\'s stock from "Overweight" to "Equal-weight", citing increased competition.' },
    { id: 'news_17', timestamp: timeAgo(155), symbol: 'CRM', headline: 'Salesforce announces new AI integrations for Slack', sentiment: 'Positive', provider: 'The Verge', preview: 'Salesforce demonstrated new "Einstein AI" features for its Slack platform, aiming to boost productivity with generative AI.' },
    { id: 'news_18', timestamp: timeAgo(170), symbol: 'XOM', headline: 'Exxon Mobil reports lower than expected quarterly profits', sentiment: 'Negative', provider: 'Bloomberg', preview: 'Falling oil prices led to Exxon Mobil reporting profits that were below Wall Street forecasts for the third quarter.' },
    { id: 'news_19', timestamp: timeAgo(185), symbol: 'PFE', headline: 'Pfizer gets FDA approval for new vaccine', sentiment: 'Positive', provider: 'Reuters', preview: 'The U.S. Food and Drug Administration has granted full approval for Pfizer\'s new respiratory syncytial virus (RSV) vaccine.' },
    { id: 'news_20', timestamp: timeAgo(200), symbol: 'WMT', headline: 'Walmart to expand drone delivery service to 5 new states', sentiment: 'Positive', provider: 'CNBC', preview: 'Walmart is significantly expanding its drone delivery partnership with DroneUp, planning to cover up to 4 million households.' },
    { id: 'news_21', timestamp: timeAgo(215), symbol: 'INTC', headline: 'Intel delays new chip factory opening', sentiment: 'Negative', provider: 'WSJ', preview: 'Intel has announced a delay in the opening of its new semiconductor fabrication plant in Ohio, pushing the timeline back by six months.' },
    { id: 'news_22', timestamp: timeAgo(230), symbol: 'PYPL', headline: 'PayPal launches new checkout feature for small businesses', sentiment: 'Neutral', provider: 'TechCrunch', preview: 'PayPal is introducing a new "fast lane" checkout experience, aiming to improve conversion rates for its small business customers.' },
    { id: 'news_23', timestamp: timeAgo(245), symbol: 'SBUX', headline: 'Starbucks unionization efforts grow in major cities', sentiment: 'Neutral', provider: 'MarketWatch', preview: 'Workers at several more Starbucks locations in major U.S. cities have voted to unionize, continuing a nationwide trend.' },
    { id: 'news_24', timestamp: timeAgo(260), symbol: 'BA', headline: 'Boeing secures massive order from international airline', sentiment: 'Positive', provider: 'Bloomberg', preview: 'Boeing has finalized a major order for its 787 Dreamliner aircraft with a leading international airline, boosting its order backlog.' },
    { id: 'news_25', timestamp: timeAgo(275), symbol: 'CSCO', headline: 'Cisco acquires cybersecurity firm for $2B', sentiment: 'Positive', provider: 'Reuters', preview: 'Cisco Systems has announced its intent to acquire a fast-growing cybersecurity startup for approximately $2 billion in cash and stock.' },
];
